# This is a basic workflow to help you get started with Actions

name: CI


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
   runs-on: ubuntu-latest
   steps: 
     - uses: actions/checkout@v3
     - name: Setup dotnet
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: |
           8.0.x
     - name: Create test project
       run: dotnet new nunit

     - name: Show me the test file
       run: cat UnitTest1.cs

     - name: Run the test
       run: dotnet test
     - name: print out the stuff
       run: (sleep 5 && echo "this is after sleeping 5 seconds, printed at $(date)") & echo "this is async, printed at $(date)"


