name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Use v2 to specify a specific repository
        with:
          repository: uldahlalex/NewsAPITests  # The GitHub repository you want to clone
          ref: main  # The branch you want to check out (change as needed)
      
      # Rest of your workflow steps
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x

      - name: Build and test
        run: |
          cd NewsAPITests  # Navigate to the repository directory
          dotnet build
          dotnet test
          
      - name: open api
        run: |
          (dotnet new webapi && dotnet run --urls=http://localhost:5000) &
          (sleep 20 && kill -9 $(lsof -t -i:5000))
      
      - name: print out the stuff
        run: |
          (sleep 5 && echo "this is after sleeping 5 seconds, printed at $(date)") &
          echo "this is async, printed at $(date)"
